### ISSUE TITLE
MediaConvert does not have sufficient permissions to read from external S3 bucket

### ISSUE THREAD

**Issue by jkielbaey** [aws-solutions/content-localization-on-aws#325]
**Describe the bug**

When starting a workflow using an S3 trigger, MediaConvert is not granted permissions to read objects from the external S3 bucket. The IAM role created to grant these permissions to MediaConvert only lists the bucket in the relevant resource property of the policy statement. 

The issue appears to be with the OperatorLibrary nested stack.

```yaml
  mediaConvertS3Role:
    Type: "AWS::IAM::Role"
    ...
      Policies:
        - PolicyName: "MediaconvertAllowS3"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                Resource: !Sub "arn:aws:s3:::${DataPlaneBucket}/*"
                Effect: "Allow"
              - Action:
                  - "s3:GetObject"
                Resource: !If ["AllowAccessToExternalBucket", !Sub "${ExternalBucketArn}", !Sub "arn:aws:s3:::${DataPlaneBucket}/*"]
                Effect: "Allow"
      Tags:
        - Key: "environment"
          Value: "mie"
```

The line `Resource: !If ["AllowAccessToExternalBucket", !Sub "${ExternalBucketArn}", !Sub "arn:aws:s3:::${DataPlaneBucket}/*"]` should be `Resource: !If ["AllowAccessToExternalBucket", !Sub "${ExternalBucketArn}/*", !Sub "arn:aws:s3:::${DataPlaneBucket}/*"]`

**Expected behavior**

The IAM role mentioned above should also be granted GetObject permissions on the objects inside the S3 bucket.

**Please complete the following information about the solution:**

- [ ] Version: [e.g. v1.0.0]

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "_(SO0021) - Video On Demand workflow with AWS Step Functions, MediaConvert, MediaPackage, S3, CloudFront and DynamoDB. Version **v5.0.0**_". If the description does not contain the version information, you can look at the mappings section of the template:

```yaml
Mappings:
  MediaInsightsEngine:
    Release:
      Version: "v4.0.1"
  Application:
    SourceCode:
      GlobalS3Bucket: "elementalrodeo99-eu-central-1"
      TemplateKeyPrefix: "content-localization-on-aws/mie-1645122686"
      RegionalS3Bucket: "elementalrodeo99"
      CodeKeyPrefix: "content-localization-on-aws/mie-1645122686"
      Version: "mie-1645122686"
```

- [ ] Region: eu-central-1

- [ ] Was the solution modified from the version published on this repository?

- [ ] If the answer to the previous question was yes, are the changes available on GitHub?

- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?

- [ ] Were there any errors in the CloudWatch Logs?
